"""
VisionGuard — Base Event Detector
Abstract base class for all event detectors.
Implements temporal sliding window and risk scoring framework.
"""
import time
from abc import ABC, abstractmethod
from typing import List, Dict, Optional, Any
from dataclasses import dataclass, field
from collections import deque

from ai.pipeline import FrameAnalysis

import config


@dataclass
class EventAlert:
    """An alert generated by an event detector."""
    event_type: str                  # fire, fight, robbery, etc.
    risk_score: int                  # 0-100
    risk_level: str                  # CRITICAL, HIGH, MEDIUM, LOW
    confidence: float                # 0.0-1.0
    description: str                 # Human-readable description
    details: Dict[str, Any] = field(default_factory=dict)  # Event-specific details
    timestamp: float = field(default_factory=time.time)
    duration_seconds: float = 0.0    # How long the event has persisted
    department: str = ""             # Which department to contact
    dial: str = ""                   # Phone number
    priority: str = ""               # CRITICAL, HIGH, MEDIUM, LOW
    action: str = ""                 # AUTO_DISPATCH, TEAM_REVIEW, LOG_ONLY
    frame_number: int = 0
    evidence_path: Optional[str] = None

    def __post_init__(self):
        # Set risk level based on score
        if self.risk_score >= 85:
            self.risk_level = "CRITICAL"
            self.action = "AUTO_DISPATCH"
        elif self.risk_score >= 50:
            self.risk_level = "HIGH"
            self.action = "TEAM_REVIEW"
        elif self.risk_score >= 25:
            self.risk_level = "MEDIUM"
            self.action = "LOG_ONLY"
        else:
            self.risk_level = "LOW"
            self.action = "LOG_ONLY"

        # Set department routing
        routing = config.DEPARTMENT_ROUTING.get(self.event_type, {})
        self.department = routing.get("dept", "Unknown")
        self.dial = routing.get("dial", "N/A")
        self.priority = routing.get("priority", "MEDIUM")


class BaseEventDetector(ABC):
    """
    Abstract base class for all event detectors.
    
    Each detector:
    1. extract_signals() — extracts relevant signals from the frame analysis
    2. calculate_risk() — calculates a risk score from the signal window
    3. check() — main method called by the event engine
    
    Uses a temporal sliding window to require PERSISTENCE before triggering.
    """

    def __init__(self, event_type: str, window_seconds: float = None):
        self.event_type = event_type
        self.window_seconds = window_seconds or config.EVENT_WINDOW_SECONDS
        self.min_persistence = config.EVENT_MIN_PERSISTENCE_SECONDS

        # Temporal sliding window of signal snapshots
        self._signal_window: deque = deque()
        self._event_start_time: Optional[float] = None
        self._last_alert: Optional[EventAlert] = None
        self._alert_cooldown: float = 3.0  # Don't re-alert within 3 seconds
        self._last_alert_time: float = 0.0
        self._grace_period: float = 1.5    # Tolerate 1.5s gaps in detection (YOLO flicker)
        self._last_signal_time: float = 0.0

    @abstractmethod
    def extract_signals(self, analysis: FrameAnalysis) -> Optional[Dict[str, Any]]:
        """
        Extract event-relevant signals from the current frame analysis.
        Return a dict of signals, or None if nothing relevant detected.
        """
        pass

    @abstractmethod
    def calculate_risk(self, signal_window: List[Dict[str, Any]]) -> int:
        """
        Calculate risk score (0-100) from the signal window.
        The window contains multiple frames of signals.
        """
        pass

    def check(self, analysis: FrameAnalysis) -> Optional[EventAlert]:
        """
        Main check method called every AI frame.
        
        1. Extract signals from current frame
        2. Add to temporal window
        3. Clean old signals from window
        4. If enough signals persist, calculate risk
        5. If risk exceeds threshold, generate alert
        
        Uses a grace period so intermittent detections (YOLO flickering)
        don't reset the persistence timer.
        """
        now = time.time()

        # Extract signals
        signals = self.extract_signals(analysis)

        if signals is not None:
            signals["_timestamp"] = now
            signals["_frame"] = analysis.frame_number
            self._signal_window.append(signals)
            self._last_signal_time = now

            if self._event_start_time is None:
                self._event_start_time = now
        else:
            # Grace period — tolerate brief gaps in detection (YOLO flickering)
            # Only reset if no signal for > grace period
            if (self._event_start_time is not None and
                    (now - self._last_signal_time) > self._grace_period):
                self._event_start_time = None

        # Clean old signals from window
        cutoff = now - self.window_seconds
        while self._signal_window and self._signal_window[0]["_timestamp"] < cutoff:
            self._signal_window.popleft()

        # Need minimum persistence before triggering
        if self._event_start_time is None:
            return None

        duration = now - self._event_start_time
        if duration < self.min_persistence:
            return None

        # Check cooldown
        if (now - self._last_alert_time) < self._alert_cooldown:
            return None

        # Calculate risk from signal window
        if len(self._signal_window) < 1:
            return None

        window_list = list(self._signal_window)
        risk_score = self.calculate_risk(window_list)

        if risk_score < 25:  # Below minimum threshold
            return None

        # Generate alert
        latest = window_list[-1]
        description = self._build_description(latest, risk_score, duration)

        alert = EventAlert(
            event_type=self.event_type,
            risk_score=risk_score,
            risk_level="",  # Set in __post_init__
            confidence=risk_score / 100.0,
            description=description,
            details=latest,
            duration_seconds=round(duration, 1),
            frame_number=analysis.frame_number,
        )

        self._last_alert = alert
        self._last_alert_time = now

        return alert

    def _build_description(self, signals: Dict, risk_score: int, duration: float) -> str:
        """Build a basic description. Override for custom descriptions."""
        return (
            f"{self.event_type.upper()} detected | "
            f"Risk: {risk_score}% | "
            f"Duration: {duration:.1f}s"
        )

    def reset(self):
        """Reset the detector state."""
        self._signal_window.clear()
        self._event_start_time = None
        self._last_alert = None
        self._last_alert_time = 0.0
        self._last_signal_time = 0.0
